//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.IO

	public class RN
	{
	public class GetL(){
	StreamReader streamReader = new StreamReader(C:\Users\cmathies\Desktop\GitHub\WRITING-PLUGINS\Text); // in the text folder. Have to reasign.
		string text = streamReader.ReadToEnd();
		streamReader.Close();

	}
}

